FROM php:7.4-apache
ENV EXT_APCU_VERSION=5.1.17
RUN docker-php-ext-install mysqli
#RUN pecl install xdebug-3.0.3
#RUN docker-php-ext-enable xdebug
#RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/php.ini
RUN apt-get update  \
    && apt-get install -y libzip-dev zip \
    && docker-php-ext-install zip pdo_mysql pdo exif
RUN apt-get -y update \
    && apt-get install -y libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl
RUN cd ~  \
    && curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
RUN a2enmod rewrite
RUN service apache2 restart
RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && architecture=$(uname -m) \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/$architecture/$version \
    && mkdir -p /tmp/blackfire \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
    && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8307\n" > $PHP_INI_DIR/conf.d/blackfire.ini \
    && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz
#RUN chown www-data:www-data /var/www/html/
#RUN groupadd dev -g 1001
#RUN useradd dev -g dev -d /home/dev -m
#RUN echo '%dev ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
#USER dev:dev