<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTBz0Bte\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTBz0Bte/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTBz0Bte.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTBz0Bte\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTBz0Bte\App_KernelProdContainer([
    'container.build_hash' => 'TBz0Bte',
    'container.build_id' => 'b47c503d',
    'container.build_time' => 1638641923,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTBz0Bte');
