<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::indexAction'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'task_list' => [[], ['_controller' => 'App\\Controller\\TaskController::index'], [], [['text', '/tasks/']], [], [], []],
    'task_create' => [[], ['_controller' => 'App\\Controller\\TaskController::new'], [], [['text', '/tasks/create']], [], [], []],
    'task_edit' => [['id'], ['_controller' => 'App\\Controller\\TaskController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'task_toggle' => [['id'], ['_controller' => 'App\\Controller\\TaskController::toggleTaskAction'], [], [['text', '/toggle'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'task_delete' => [['id'], ['_controller' => 'App\\Controller\\TaskController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/users/']], [], [], []],
    'user_create' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/users/create']], [], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], [], []],
];
