<?php

namespace ContainerEXtlM7t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BkqKRZVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bkqKRZV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bkqKRZV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\TaskController::delete' => ['privates', '.service_locator.TfvLzuL', 'get_ServiceLocator_TfvLzuLService', true],
            'App\\Controller\\TaskController::edit' => ['privates', '.service_locator.TfvLzuL', 'get_ServiceLocator_TfvLzuLService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.OSbocZ8', 'get_ServiceLocator_OSbocZ8Service', true],
            'App\\Controller\\TaskController::toggleTaskAction' => ['privates', '.service_locator.TfvLzuL', 'get_ServiceLocator_TfvLzuLService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.uRo09ni', 'get_ServiceLocator_URo09niService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.CbHXbps', 'get_ServiceLocator_CbHXbpsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\TaskController:delete' => ['privates', '.service_locator.TfvLzuL', 'get_ServiceLocator_TfvLzuLService', true],
            'App\\Controller\\TaskController:edit' => ['privates', '.service_locator.TfvLzuL', 'get_ServiceLocator_TfvLzuLService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.OSbocZ8', 'get_ServiceLocator_OSbocZ8Service', true],
            'App\\Controller\\TaskController:toggleTaskAction' => ['privates', '.service_locator.TfvLzuL', 'get_ServiceLocator_TfvLzuLService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.uRo09ni', 'get_ServiceLocator_URo09niService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.CbHXbps', 'get_ServiceLocator_CbHXbpsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TaskController::delete' => '?',
            'App\\Controller\\TaskController::edit' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\TaskController::toggleTaskAction' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TaskController:delete' => '?',
            'App\\Controller\\TaskController:edit' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\TaskController:toggleTaskAction' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
