<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvmQkxo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvmQkxo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVvmQkxo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVvmQkxo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVvmQkxo\App_KernelDevDebugContainer([
    'container.build_hash' => 'VvmQkxo',
    'container.build_id' => '0aa08dc5',
    'container.build_time' => 1638700872,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVvmQkxo');
